version: "3.8"

services:
  bmi-calculator:
    image: nginx:alpine
    container_name: bmi-calculator
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped
